### ISSUE TITLE
Feature Request: "regular" chat mode

### ISSUE THREAD

**Issue by joelmellon** [junyu-w/gptc#1]
I'm loving gptc so far!

Any possibility of adding an option to do a "regular" chat mode to be able to chat about non-bash or shell related things?

An option to go straight into a normal chat would be really cool. Basically just ChatGPT on the CLI. Something like:

`gptc -c`

This is an amazing idea, by the way. 10/10!

**Comment by junyu-w** [comment]
I'm glad you liked it and I like the idea! I'll build it when I find some time so stay tuned for the next release with this feature 🙌

**Comment by perdakovich** [comment]
I agree

**Comment by junyu-w** [comment]
@joelmellon - v1.1.0 has been released and you can now type `gptc chat` to start an interactive chat directly!
