### ISSUE TITLE
How to use GPT-4 in this program?

### ISSUE THREAD

**Issue by perdakovich** [junyu-w/gptc#2]
what values are available for "model" variable in the config?

I tried to set gpt4, gpt-4, GPT4, but when I start chatting and ask "who are you" it says it's gpt-3 and it's the newest version of gpt.

also, do I need to buy ChatGPT Plus to use GPT4? If yes, then what happens if one doesn't have Plus and tries to use GPT4?

Maybe I can't use GPT4 because I don't have Plus and it fallbacks to GPT-3?

**Comment by junyu-w** [comment]
Hi @goosegit11 , I believe gpt-4 is the right value but it's currently in beta so not open to all users unless you have early access, I've had no luck with it myself. 

For the detailed list of model values you can find them at https://platform.openai.com/docs/models and click into each one. It's probably a good idea for me to add this link to the configuration prompt... next version!

**Comment by junyu-w** [comment]
@goosegit11 The link to the models page has been added to v1.1.0 to notes printed as part of the configure command when you type `gptc configure` or `gptc c`. Additionally you can type `gptc chat` to start a chat directly

**Comment by perdakovich** [comment]
cool, thanks
